### ISSUE TITLE
Force Close on Nexus4 (CM10.1-stable burild)

### ISSUE THREAD

**Issue by pureexe** [rhoadster91/FloatingSoftKeys#1]
I try to build your sourcecode but it get force close on

myshell.getShell(true);

i use Roottools-2.6

what version you of roottools you choose to build it without force close?

**Comment by rhoadster91** [comment]
I also compiled using RootTools-2.6
Can you please specify what exception is being raised in the LogCat??

**Comment by pureexe** [comment]
Thankyou for your attention
Now I run without forceclose :D

**Comment by rhoadster91** [comment]
I am glad. :) Don't hesitate to make improvements and send pull requests.
