### ISSUE TITLE
#2 from play store.

### ISSUE THREAD

**Issue by Efreak** [rhoadster91/FloatingSoftKeys#4]
Allow collapsing the entire thing to a single menu button, so I can have these nice large buttons, but they don't get in the way when I'm playing games.

In other words, allow collapsing the all three buttons down to one. I have my buttons set rather to a rather large size (twitchy fingers again), and they block things when I'm playing games and using other apps that make use of the entire screen. Basically, I'm asking for a way to hide all but one of the buttons.

**Comment by rhoadster91** [comment]
You can long press back button and it collapses the bar to the left edge of the screen to the size of a single button. Re-clicking on this button will expand the bar again.
